language: julia
notifications:
  email: false
sudo: fals
os:
  - linux
julia:
  - release
  - nightly
script:
  - echo $TRAVIS_JULIA_VERSION
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia --color=yes --code-coverage test/runtests.jl; fi
  - if [ $TRAVIS_JULIA_VERSION = "release" ]; then julia --color=yes test/runtests.jl; fi
  - julia --color=yes TestCases/runtests.jl
after_success:
  - julia -e 'if VERSION >= v"0.4-"; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder("juliacat")); end'
