language: julia
os:
  - linux
julia:
  - release
  - nightly
script:
  - julia --code-coverage test/runtests.jl
  - julia --color=yes TestCases/runtests.jl
after_success:
- julia -e 'Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder("juliacat"))'
