!(VERSION.minor > 3) && println("Required Julia 0.4")

  ArgumentError
  AssertionError
  Base.LinAlg.ARPACKException
  Base.LinAlg.LAPACKException
  Base.LinAlg.PosDefException
  Base.LinAlg.RankDeficientException
  Base.LinAlg.SingularException
  Base.Math.AmosException
  Base.Pkg.Resolve.MaxSum.UnsatError
  Base.PrecompilableError
  Base.SimdLoop.SimdError
  Base.SparseMatrix.CHOLMOD.CHOLMODException
  Base.SparseMatrix.UMFPACK.MatrixIllConditionedException
  Base.UVError
  Base.WrappedException
  BoundsError
  CompositeException
  DimensionMismatch
  DivideError
  DomainError
  EOFError
  ErrorException
  InexactError
  InterruptException
  InvalidStateException
  KeyError
  MethodError
  NullException
  OutOfMemoryError
  OverflowError
  ParseError
  ProcessExitedException
  ReadOnlyMemoryError
  RemoteException
  SegmentationFault
  StackOverflowError
  SystemError
  TypeError
  UndefRefError
  UndefVarError
  UnicodeError
